{{- if eq .Values.global.prometheusLocation "on-cluster" }}
{{- if (index .Values "exporters" "kube-state-metrics" "enabled") }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: drycc-kube-state-metrics
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ index .Values "imageTag" }}
spec:
  selector:
    matchLabels:
      app: drycc-kube-state-metrics
  replicas: {{ index .Values "kube-state-metrics" "replicas" }}
  serviceName: drycc-kube-state-metrics
  volumeClaimTemplates: []
  template:
    metadata:
      labels:
        app: drycc-kube-state-metrics
    spec:
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" ( index .Values "kube-state-metrics" "podAffinityPreset" "type") "key" ( index .Values "kube-state-metrics" "podAffinityPreset" "key") "values" ( index .Values "kube-state-metrics" "podAffinityPreset" "values" ) ) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" ( index .Values "kube-state-metrics" "podAntiAffinityPreset" "type") "key" ( index .Values "kube-state-metrics" "podAntiAffinityPreset" "key") "values" ( index .Values "kube-state-metrics" "podAntiAffinityPreset" "values" ) ) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" ( index .Values "kube-state-metrics" "nodeAffinityPreset" "type") "key" ( index .Values "kube-state-metrics" "nodeAffinityPreset" "key") "values" ( index .Values "kube-state-metrics" "nodeAffinityPreset" "values" ) ) | nindent 10 }}
      hostNetwork: {{ index .Values "kube-state-metrics" "hostNetwork" }}
      containers:
      - name: drycc-kube-state-metrics
        image: {{ .Values.imageRegistry }}/{{ .Values.imageOrg }}/prometheus:{{ .Values.imageTag }}
        imagePullPolicy: {{.Values.imagePullPolicy}}
        args:
        - kube-state-metrics
        {{-  if (index .Values "kube-state-metrics" "extraArgs") }}
        {{- index .Values "kube-state-metrics" "extraArgs" | toYaml | nindent 8 }}
        {{-  end  }}
        - --port=8080
        {{-  if (index .Values "kube-state-metrics" "collectors")  }}
        - --resources={{ index .Values "kube-state-metrics" "collectors" | join "," }}
        {{-  end  }}
        {{- if (index .Values "kube-state-metrics" "metricLabelsAllowlist") }}
        - --metric-labels-allowlist={{ index .Values "kube-state-metrics" "metricLabelsAllowlist" | join "," }}
        {{- end }}
        {{- if (index .Values "kube-state-metrics" "metricAnnotationsAllowList") }}
        - --metric-annotations-allowlist={{ index .Values "kube-state-metrics" "metricAnnotationsAllowList" | join "," }}
        {{- end }}
        {{- if (index .Values "kube-state-metrics" "metricAllowlist") }}
        - --metric-allowlist={{ index .Values "kube-state-metrics" "metricAllowlist" | join "," }}
        {{- end }}
        {{- if (index .Values "kube-state-metrics" "metricDenylist") }}
        - --metric-denylist={{ index .Values "kube-state-metrics" "metricDenylist" | join "," }}
        {{- end }}
        {{- $namespaces := list }}
        {{- if (index .Values "kube-state-metrics" "namespaces") }}
        {{- range $ns := join "," (index .Values "kube-state-metrics" "namespaces") | split "," }}
        {{- $namespaces = append $namespaces (tpl $ns $) }}
        {{- end }}
        {{- end }}
        {{- if (index .Values "kube-state-metrics" "releaseNamespace") }}
        {{- $namespaces = append $namespaces ( .Release.Namespace ) }}
        {{- end }}
        {{- if $namespaces }}
        - --namespaces={{ $namespaces | mustUniq | join "," }}
        {{- end }}
        {{- if (index .Values "kube-state-metrics" "namespacesDenylist") }}
        - --namespaces-denylist={{ tpl (index .Values "kube-state-metrics" "namespacesDenylist" | join ",") $ }}
        {{- end }}
        - --pod=$(POD_NAME)
        - --pod-namespace=$(POD_NAMESPACE)
        {{- if (index .Values "kube-state-metrics" "kubeconfig" "enabled") }}
        - --kubeconfig=/opt/k8s/.kube/config
        {{- end }}
        {{- if (index .Values "kube-state-metrics" "selfMonitor" "telemetryHost") }}
        - --telemetry-host={{ index .Values "kube-state-metrics" "selfMonitor" "telemetryHost" }}
        {{- end }}
        {{- if (index .Values "kube-state-metrics" "selfMonitor" "telemetryPort") }}
        - --telemetry-port={{ index .Values "kube-state-metrics" "selfMonitor" "telemetryPort" | default 8081 }}
        {{- end }}
        {{- if or (index .Values "kube-state-metrics" "kubeconfig" "enabled") (index .Values "kube-state-metrics" "volumeMounts") }}
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
        {{- if (index .Values "kube-state-metrics" "kubeconfig" "enabled") }}
        - name: kubeconfig
          mountPath: /opt/k8s/.kube/
          readOnly: true
        {{- end }}
        {{- if (index .Values "kube-state-metrics" "volumeMounts") }}
{{ toYaml index .Values "kube-state-metrics" "volumeMounts" | indent 8 }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: 8080
          name: "http"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
      {{- if or (index .Values "kube-state-metrics" "kubeconfig" "enabled") (index .Values "kube-state-metrics" "volumes") }}
      volumes:
      {{- if (index .Values "kube-state-metrics" "kubeconfig" "enabled")}}
        - name: kubeconfig
          secret:
            secretName: kube-state-metrics-kubeconfig
      {{- end }}
      {{- if (index .Values "kube-state-metrics" "volumes") }}
{{ toYaml index .Values "kube-state-metrics" "volumes" | indent 8 }}
      {{- end }}
      {{- end }}
{{- end }}
{{- end }}
