{{- if eq .Values.global.prometheusLocation "on-cluster" }}
{{- if (index .Values "exporters" "kube-state-metrics" "enabled") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: drycc-stsdiscovery-kube-state-metrics
  labels:
    app: drycc-kube-state-metrics
    heritage: drycc
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resourceNames:
  - drycc-kube-state-metrics
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
{{- end }}
{{- end }}
