{{- if eq .Values.global.prometheusLocation "on-cluster" }}
{{- if (index .Values "exporters" "kube-state-metrics" "enabled") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: drycc-stsdiscovery-kube-state-metrics
  labels:
    app: drycc-kube-state-metrics
    heritage: drycc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: drycc-stsdiscovery-kube-state-metrics
subjects:
  - kind: ServiceAccount
    name: drycc-kube-state-metrics
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
