{{- if eq .Values.global.prometheusLocation "on-cluster" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: drycc-prometheus
  labels:
    heritage: drycc
data:
  allow-snippet-annotations: "false"
{{- $root := . -}}
{{- range $key, $value := .Values.prometheusFiles }}
{{ $key | indent 2 }}: |
{{ toYaml $value | indent 4 }}
{{- end }}
{{- end }}
