{{- if eq .Values.global.prometheusLocation "on-cluster" }}
{{- $platformDomain := .Values.global.platformDomain }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: drycc-prometheus
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
spec:
  serviceName: drycc-prometheus-headless
  replicas: {{ .Values.prometheus-server.replicas }}
  selector:
    matchLabels:
      app: drycc-prometheus
  template:
    metadata:
      labels:
        app: drycc-prometheus
    spec:
      serviceAccount: drycc-prometheus
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.prometheus-server.podAffinityPreset.type "key" .Values.prometheus-server.podAffinityPreset.key "values" .Values.prometheus-server.podAffinityPreset.values ) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.prometheus-server.podAntiAffinityPreset.type "key" .Values.prometheus-server.podAntiAffinityPreset.key "values" .Values.prometheus-server.podAntiAffinityPreset.values ) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.prometheus-server.nodeAffinityPreset.type "key" .Values.prometheus-server.nodeAffinityPreset.key "values" .Values.prometheus-server.nodeAffinityPreset.values ) | nindent 10 }}
      containers:
      - name: drycc-prometheus
        image: {{ .Values.imageRegistry }}/{{ .Values.imageOrg }}/prometheus:{{ .Values.imageTag }}
        imagePullPolicy: {{.Values.imagePullPolicy}}
        args:
          - prometheus
          - --web.route-prefix=/
          - --storage.tsdb.retention.time={{ .Values.prometheus-server.retention }}
          - --config.file=/opt/drycc/prometheus/config/prometheus.yaml
          - --storage.tsdb.path=/data
          - --web.console.libraries=/opt/drycc/console_libraries
          - --web.console.templates=/opt/drycc/prometheus/consoles
          {{- range .Values.prometheus-server.extraFlags }}
          - --{{ . }}
          {{- end }}
          {{- range $key, $value := .Values.prometheus-server.extraArgs }}
          - --{{ $key }}={{ $value }}
          {{- end }}
          - --web.external-url=http://prometheus.{{ $platformDomain }}
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /-/healthy
            port: web
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        ports:
        - containerPort: 9090
          name: web
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /-/ready
            port: web
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources: {}
        startupProbe:
          failureThreshold: 60
          httpGet:
            path: /-/ready
            port: web
            scheme: HTTP
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 3
  {{- if not .Values.prometheus-server.persistence.enabled }}
        - name: prometheus-data
          emptyDir: {}
  {{- else }}
  volumeClaimTemplates:
  - metadata:
      name: prometheus-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.prometheus-server.persistence.storageClass }}
      {{- if (eq "-" .Values.prometheus-server.persistence.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: "{{ .Values.prometheus-server.persistence.storageClass }}"
      {{- end }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.prometheus-server.persistence.size | quote }}
  {{- end }}
{{- end }}
