{{- if eq .Values.global.prometheusLocation "on-cluster" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s:drycc-prometheus" .Release.Namespace | quote }}  
  labels:
    app: drycc-prometheus
    heritage: drycc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s:drycc-prometheus" .Release.Namespace | quote }}
subjects:
- kind: ServiceAccount
  name: drycc-prometheus
  namespace: {{ .Release.Namespace }}
{{- end }}
