{{- if eq .Values.global.prometheusLocation "off-cluster" }}
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-creds
  labels:
    heritage: drycc
type: Opaque
data:
  url: {{ .Values.url | b64enc }}
{{- end }}
