{{- if eq .Values.global.prometheusLocation "on-cluster" }}
{{- if (index .Values "kube-state-metrics" "enabled") }}
apiVersion: v1
kind: Service
metadata:
  name: drycc-kube-state-metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
    {{- with index .Values "kube-state-metrics" "service" "annotations" }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    heritage: drycc
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: drycc-kube-state-metrics
{{- end }}
{{- end }}
